# Generated by Django 5.1.1 on 2024-09-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overwatch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maps",
            name="Mode",
            field=models.CharField(
                choices=[
                    ("clash", "Clash"),
                    ("control", "control"),
                    ("escort", "Escort"),
                    ("flashpoint", "Flashpoint"),
                    ("hybrid", "Hybrid"),
                    ("push", "Push"),
                ],
                default=None,
                max_length=32,
            ),
        ),
    ]
